"""make gym_id nullable

Revision ID: 6cd1e0071d31
Revises: 2560b301dcd8
Create Date: 2026-04-05 14:47:40.386859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd1e0071d31'
down_revision: Union[str, Sequence[str], None] = '2560b301dcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'gym_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'gym_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
