"""add full_name phone to user

Revision ID: dcfbb6e90dd2
Revises: 6cd1e0071d31
Create Date: 2026-04-05 15:03:41.888627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfbb6e90dd2'
down_revision: Union[str, Sequence[str], None] = '6cd1e0071d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_phone_key'), 'clients', type_='unique')
    op.drop_column('clients', 'full_name')
    op.drop_column('clients', 'phone')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('clients_phone_key'), 'clients', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
